Removed log from multiproc as this causes the following traceback
Starting ChemRefDataDbUtils loadChemCompMulti
Traceback (most recent call last):
  File "/nfs/msd/services/onedep/resources/onedep_checkouts/git/staging/py-wwpdb_apps_chem_ref_data/wwpdb/apps/chem_ref_data/utils/ChemRe
fDataDbUtils.py", line 275, in loadChemCompMulti
    mpu = MultiProcUtil(verbose=True, log=self.__lfh)
TypeError: __init__() got an unexpected keyword argument 'log'